/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ActiveX { 
  DISABLED, ENABLED, NOT_SUPPORTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ActiveX\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"DISABLED\",\"ENABLED\",\"NOT_SUPPORTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
